# for running the whole stack locally in Docker containers
version: '3.3'
services:

  db:
    image: "mysql"
    container_name: db
    ports:
      - 3306:3306
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=ineor
      - MYSQL_DATABASE=ineor

  api:
    build: ./IneorTaskBackend
    container_name: api
    ports:
      - 5001:5001
    restart: always
    links:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - PORT=5001

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - 80:80
    restart: always
    links:
      - api
    environment:
      - ENVIRONMENT=staging
      - PORT=80

volumes:
  data:
